package com.sample

//Importovanje Java klase koja predstavlja cinjenice
import com.sample.SistemGrejanja;
 
rule "Pravilo 1"
    when
        sg : SistemGrejanja( osetljiviNaHladnocu == "Veoma" && tipSistema == null )
    then
    	sg.setTipSistema("centralni");
        update( sg );
end

rule "Pravilo 2"
    when
        sg : SistemGrejanja( (osetljiviNaHladnocu == "Onako" || osetljiviNaHladnocu == "Ne") 
        						&& povrsina < 50 && tipSistema == null )
    then
    	sg.setTipSistema("necentralizovan");
        update( sg );
end

rule "Pravilo 3"
    when
        sg : SistemGrejanja( (osetljiviNaHladnocu == "Onako" || osetljiviNaHladnocu == "Ne") 
        						&& povrsina >= 50 && tipSistema == null )
    then
    	sg.setTipSistema("centralni");
        update( sg );
end

rule "Pravilo 4"
    when
        sg : SistemGrejanja( tipSistema == "centralni" && cenaStoNiza == false 
        					&& imaGas == true && konkretanSistem == null)
    then
    	sg.setKonkretanSistem("Centralno grejanje na gas");
        update( sg );
end

rule "Pravilo 5"
    when
        sg : SistemGrejanja( tipSistema == "centralni" && cenaStoNiza == false 
        					&& imaGradskoGrejanje == true && konkretanSistem == null)
    then
    	sg.setKonkretanSistem("Centralno grejanje preko gradske mreže (toplana)");
        update( sg );
end

rule "Pravilo 6"
    when
        sg : SistemGrejanja( tipSistema == "centralni" && cenaStoNiza == false 
        					&& imaStruju == true && imaGas == false
        					&& imaGradskoGrejanje == false && konkretanSistem == null)
    then
    	sg.setKonkretanSistem("Centralno grejanje na struju");
        update( sg );
end

rule "Pravilo 7"
    when
        sg : SistemGrejanja( tipSistema == "centralni" && cenaStoNiza == true 
        					&& konkretanSistem == null)
    then
    	sg.setKonkretanSistem("Centralno grejanje na čvrsta goriva (drvo, ugalj)");
        update( sg );
end
 
rule "Pravilo 8"
    when
        sg : SistemGrejanja( tipSistema == "necentralizovan" && imaStruju == true 
        					&& konkretanSistem == null)
    then
    	sg.setKonkretanSistem("Necentralizovano grejanje na struju (TA peć, “Norveški” radijatori)");
        update( sg );
end

rule "Pravilo 9"
    when
        sg : SistemGrejanja( tipSistema == "necentralizovan" && imaStruju == false 
        					&& konkretanSistem == null)
    then
    	sg.setKonkretanSistem("Necentralizovano grejanje na čvrsta goriva (kamin, peć na čvrsta goriva)");
        update( sg );
end
